# Generated by Django 3.2.2 on 2021-05-13 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_Active')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('email', models.CharField(blank=True, max_length=250, verbose_name='E-mail')),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DevType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_Active')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IPAddr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_Active')),
                ('dns_name', models.CharField(default='blank', max_length=15, verbose_name='DNS name')),
            ],
            options={
                'verbose_name': 'IPAddr',
                'verbose_name_plural': 'IPAddr',
            },
        ),
        migrations.CreateModel(
            name='SW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_Active')),
                ('SN', models.CharField(blank=True, max_length=32, verbose_name='S/N')),
                ('master', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='networking.customer')),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='networking.devtype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegGate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_Active')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('customer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='networking.customer')),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_Active')),
                ('SN', models.CharField(blank=True, max_length=32, verbose_name='S/N')),
                ('master', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='networking.customer')),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='networking.devtype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_Active')),
                ('cidr', models.PositiveIntegerField(choices=[(1, '/1'), (2, '/2'), (3, '/3'), (4, '/4'), (5, '/5'), (6, '/6'), (7, '/7'), (8, '/8'), (9, '/9'), (10, '/10'), (11, '/11'), (12, '/12'), (13, '/13'), (14, '/14'), (15, '/15'), (16, '/16'), (17, '/17'), (18, '/18'), (19, '/19'), (20, '/20'), (21, '/21'), (22, '/22'), (23, '/23'), (24, '/24'), (25, '/25'), (26, '/26'), (27, '/27'), (28, '/28'), (29, '/29'), (30, '/30')], default=24, verbose_name='CIDR')),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('rg', models.ManyToManyField(blank=True, to='networking.RegGate')),
                ('type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='networking.devtype')),
            ],
            options={
                'verbose_name': 'Network',
                'verbose_name_plural': 'Network',
            },
        ),
        migrations.CreateModel(
            name='NetSWInt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_Active')),
                ('mac', models.CharField(blank=True, max_length=25, verbose_name='MAC:')),
                ('ip', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='networking.ipaddr')),
                ('net_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='networking.sw')),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NetPCInt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_Active')),
                ('mac', models.CharField(blank=True, max_length=25, verbose_name='MAC:')),
                ('ip', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='networking.ipaddr')),
                ('net_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='networking.pc')),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='ipaddr',
            name='netw',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='networking.network'),
        ),
        migrations.AddField(
            model_name='ipaddr',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
