# Generated by Django 3.2.2 on 2021-05-09 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('address', models.TextField(verbose_name='Address')),
                ('email', models.CharField(max_length=250, verbose_name='E-mail')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_Active')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Company',
            },
        ),
        migrations.CreateModel(
            name='DevObjPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=100, verbose_name='S/N')),
                ('cpu_model', models.CharField(max_length=100, verbose_name='CPU model')),
                ('cpu_core_c', models.PositiveIntegerField(default=1, verbose_name='Core count')),
            ],
            options={
                'verbose_name': 'DevObjPC',
                'verbose_name_plural': 'DevObjPC',
            },
        ),
        migrations.CreateModel(
            name='DevObjSW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=100, verbose_name='S/N')),
            ],
            options={
                'verbose_name': 'DevObjSW',
                'verbose_name_plural': 'DevObjSW',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Address')),
                ('code', models.CharField(max_length=100, verbose_name='Code')),
                ('description', models.TextField(verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_Active')),
                ('company', models.ManyToManyField(related_name='place_company', to='networking.Company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Place',
                'verbose_name_plural': 'Place',
            },
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(max_length=15, verbose_name='Network')),
                ('mask', models.CharField(max_length=15, verbose_name='Mask')),
                ('cidr', models.PositiveIntegerField(default=24, verbose_name='CIDR')),
                ('pl', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='networking.place')),
            ],
            options={
                'verbose_name': 'Network',
                'verbose_name_plural': 'Network',
            },
        ),
        migrations.CreateModel(
            name='NetObj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dns_name', models.CharField(max_length=15, verbose_name='DNS name')),
                ('ip_address', models.CharField(max_length=15, verbose_name='IP-address')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='networking.network')),
            ],
            options={
                'verbose_name': 'Net_Obj',
                'verbose_name_plural': 'Net_Obj',
            },
        ),
        migrations.CreateModel(
            name='DevObjSWInt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('desc', models.CharField(max_length=100, verbose_name='Desc')),
                ('ip', models.ManyToManyField(related_name='SW_Net_Obj', to='networking.NetObj', verbose_name='Net_Obj')),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='networking.devobjsw')),
            ],
            options={
                'verbose_name': 'DevObjSWInt',
                'verbose_name_plural': 'DevObjSWInt',
            },
        ),
        migrations.CreateModel(
            name='DevObjPCInt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('desc', models.CharField(max_length=100, verbose_name='Desc')),
                ('ip', models.ManyToManyField(related_name='PC_Net_Obj', to='networking.NetObj', verbose_name='Net_Obj')),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='networking.devobjpc')),
            ],
            options={
                'verbose_name': 'DevObjPCInt',
                'verbose_name_plural': 'DevObjPCInt',
            },
        ),
    ]
