# Generated by Django 3.2.2 on 2021-05-12 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netpcint',
            name='ip',
            field=models.ManyToManyField(blank=True, related_name='ipaddr', to='networking.IPAddr'),
        ),
    ]
