# Generated by Django 3.2.2 on 2021-05-26 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('networking', '0002_auto_20210526_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='networking.devtype'),
        ),
    ]
