# Generated by Django 3.2.2 on 2021-05-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networking', '0003_auto_20210512_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='netpcint',
            name='ip',
            field=models.ManyToManyField(blank=True, to='networking.IPAddr'),
        ),
        migrations.AddField(
            model_name='netswint',
            name='ip',
            field=models.ManyToManyField(blank=True, to='networking.IPAddr'),
        ),
        migrations.AlterField(
            model_name='network',
            name='cidr',
            field=models.PositiveIntegerField(choices=[(1, '/1'), (2, '/2'), (3, '/3'), (4, '/4'), (5, '/5'), (6, '/6'), (7, '/7'), (8, '/8'), (9, '/9'), (10, '/10'), (11, '/11'), (12, '/12'), (13, '/13'), (14, '/14'), (15, '/15'), (16, '/16'), (17, '/17'), (18, '/18'), (19, '/19'), (20, '/20'), (21, '/21'), (22, '/22'), (23, '/23'), (24, '/24'), (25, '/25'), (26, '/26'), (27, '/27'), (28, '/28'), (29, '/29'), (30, '/30')], default=24, verbose_name='CIDR'),
        ),
    ]
